from enum import Enum


class AssistantIntent(str, Enum):
    MAKE_CHEAPER = "MAKE_CHEAPER"
    UPGRADE_HOTEL = "UPGRADE_HOTEL"
    REMAINING_BUDGET = "REMAINING_BUDGET"
    ADD_ADVENTURE = "ADD_ADVENTURE"
    AVOID_CROWDS = "AVOID_CROWDS"
    CHANGE_ITINERARY = "CHANGE_ITINERARY"
    EXPLAIN_RECOMMENDATION = "EXPLAIN_RECOMMENDATION"
    HELP = "HELP"
    UNKNOWN = "UNKNOWN"